# Generated by Django 2.0.7 on 2018-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectpart',
            name='createdate',
            field=models.DateTimeField(blank=True, db_column='CreateDate', null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='editdate',
            field=models.DateTimeField(blank=True, db_column='EditDate', null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='subjectpartname',
            field=models.CharField(blank=True, db_column='SubjectPartName', max_length=100, null=True),
        ),
    ]
