# Generated by Django 2.0.7 on 2018-10-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0002_auto_20181009_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lessonid',
        ),
        migrations.AddField(
            model_name='activity',
            name='itemid',
            field=models.ForeignKey(blank=True, db_column='ItemID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Item'),
        ),
    ]
