# Generated by Django 2.0.7 on 2018-10-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0003_auto_20181010_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmittion',
            name='accountid',
            field=models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account'),
        ),
    ]
