# Generated by Django 2.0.7 on 2018-10-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0005_auto_20181010_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='subjectpartid',
            field=models.ForeignKey(blank=True, db_column='SubjectPartID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.SubjectPart'),
        ),
    ]
