# Generated by Django 2.0.7 on 2018-10-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0006_competition_subjectpartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmittion',
            name='accountid',
            field=models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account'),
        ),
        migrations.AddField(
            model_name='competitionsubmittion',
            name='content',
            field=models.TextField(blank=True, db_column='Content', null=True),
        ),
        migrations.AddField(
            model_name='competitionsubmittion',
            name='createdate',
            field=models.DateTimeField(blank=True, db_column='CreateDate', null=True),
        ),
        migrations.AddField(
            model_name='competitionsubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competitionsubmittion',
            name='editdate',
            field=models.DateTimeField(blank=True, db_column='EditDate', null=True),
        ),
        migrations.AddField(
            model_name='competitionsubmittion',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=199, null=True),
        ),
    ]
