# Generated by Django 2.0.7 on 2018-10-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0007_auto_20181011_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='editdate',
            field=models.DateTimeField(blank=True, db_column='EditDate', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Subject'),
        ),
    ]
