# Generated by Django 2.0.7 on 2018-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0009_tracking_subjectpartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='editdate',
            field=models.DateTimeField(blank=True, db_column='EditDate', null=True),
        ),
    ]
