# Generated by Django 2.0.7 on 2018-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0010_tracking_editdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=100, null=True),
        ),
    ]
