# Generated by Django 2.0.5 on 2018-10-24 06:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0011_header_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
    ]
