# Generated by Django 2.1.2 on 2018-10-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0012_auto_20181024_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReply',
            fields=[
                ('activityreplyid', models.AutoField(db_column='ActivityReplyID', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('isenable', models.IntegerField(blank=True, db_column='IsEnable', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
            ],
            options={
                'db_table': 'activityreply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectLike',
            fields=[
                ('subjectlikeid', models.AutoField(db_column='SubjectLikeID', primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_column='Status')),
                ('isenable', models.IntegerField(db_column='IsEnable')),
                ('note', models.CharField(db_column='Note', max_length=100)),
                ('accountid', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account')),
                ('subjectid', models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Subject')),
            ],
            options={
                'db_table': 'subjectlike',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='requiredactivityid',
            field=models.ForeignKey(blank=True, db_column='RequiredActivityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Activity'),
        ),
        migrations.AddField(
            model_name='activityreply',
            name='activityid',
            field=models.ForeignKey(blank=True, db_column='ActivityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Activity'),
        ),
        migrations.AddField(
            model_name='activityreply',
            name='enrollmentid',
            field=models.ForeignKey(blank=True, db_column='EnrollmentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Enrollment'),
        ),
    ]
