# Generated by Django 2.1.2 on 2018-10-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0013_auto_20181025_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.IntegerField(blank=True, db_column='Time', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='introvideo',
            field=models.CharField(blank=True, db_column='IntoVideo', max_length=100, null=True),
        ),
    ]
