# Generated by Django 2.1.2 on 2018-10-25 04:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0014_auto_20181025_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activityreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittionreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittionreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_column='Content'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='lessonreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='newsreply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='projectsharereply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='sliderunbar',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
    ]
