# Generated by Django 2.0 on 2018-11-08 01:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0015_auto_20181025_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('subjectteacherid', models.AutoField(db_column='SubjectTeacherID', primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('isenable', models.IntegerField(blank=True, db_column='IsEnable', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account')),
            ],
            options={
                'db_table': 'subjectteacher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Subject'),
        ),
    ]
