# Generated by Django 2.0 on 2018-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0016_auto_20181108_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreply',
            name='rate',
            field=models.IntegerField(blank=True, db_column='Rate', null=True),
        ),
    ]
