# Generated by Django 2.0 on 2018-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0017_activityreply_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=50000, null=True),
        ),
    ]
