# Generated by Django 2.0 on 2018-11-09 05:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0018_auto_20181108_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='avatar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Avatar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subjectpart',
            name='order',
            field=models.IntegerField(blank=True, db_column='Order', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
    ]
