# Generated by Django 2.0 on 2018-11-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0019_auto_20181109_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviromentCate',
            fields=[
                ('enviromentcateid', models.AutoField(db_column='EnviromentCateID', primary_key=True, serialize=False)),
                ('enviromentcatename', models.CharField(blank=True, db_column='EnviromentCateName', max_length=100, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('isenable', models.IntegerField(blank=True, db_column='IsEnable', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
            ],
            options={
                'db_table': 'enviromentcate',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentRateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
    ]
