# Generated by Django 2.0 on 2018-11-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0020_auto_20181112_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
    ]
