# Generated by Django 2.0 on 2018-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0021_auto_20181112_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='introvideo',
            field=models.CharField(blank=True, db_column='IntroVideo', max_length=100, null=True),
        ),
    ]
