# Generated by Django 2.0 on 2018-11-13 01:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0022_auto_20181112_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=100, null=True),
        ),
    ]
