# Generated by Django 2.0 on 2018-11-24 14:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0023_auto_20181113_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='introvideo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='IntroVideo', max_length=100, null=True),
        ),
    ]
