# Generated by Django 2.1.3 on 2018-12-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0025_auto_20181128_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('userrankid', models.AutoField(db_column='UserRankID', primary_key=True, serialize=False)),
                ('userrankname', models.CharField(blank=True, db_column='UserRankName', max_length=100, null=True)),
                ('icon', models.CharField(blank=True, db_column='Icon', max_length=100, null=True)),
                ('requiredlevel', models.IntegerField(blank=True, db_column='RequiredLevel', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
                ('enviromentcateid', models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate')),
            ],
            options={
                'db_table': 'userrank',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=200, null=True),
        ),
    ]
