# Generated by Django 2.1.3 on 2018-12-17 23:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0027_auto_20181214_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastChat',
            fields=[
                ('fastchatid', models.AutoField(db_column='FastChatID', primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('isenable', models.IntegerField(blank=True, db_column='IsEnable', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
            ],
            options={
                'db_table': 'fastchat',
                'managed': True,
            },
        ),
    ]
