# Generated by Django 2.1.3 on 2018-12-20 03:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0028_fastchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.AutoField(db_column='ContactID', primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=100, null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account')),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='competition',
            name='subjectpartid',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='subjectpartid',
        ),
        migrations.RemoveField(
            model_name='news',
            name='subjectpartid',
        ),
        migrations.RemoveField(
            model_name='projectshare',
            name='subjectpartid',
        ),
        migrations.AddField(
            model_name='competition',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.SubjectPart'),
        ),
        migrations.AddField(
            model_name='forum',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
        migrations.AddField(
            model_name='news',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.SubjectPart'),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.SubjectPart'),
        ),
    ]
