# Generated by Django 2.1.3 on 2018-12-21 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0029_auto_20181220_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='competition',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
        migrations.AlterModelTable(
            name='userdetail',
            table='userdetail',
        ),
    ]
