# Generated by Django 2.1.3 on 2019-01-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0030_auto_20181221_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Subject'),
        ),
        migrations.AlterField(
            model_name='news',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='enviromentcateid',
            field=models.ForeignKey(blank=True, db_column='EnviromentCateID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.EnviromentCate'),
        ),
    ]
