# Generated by Django 2.1.3 on 2019-01-08 00:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0031_auto_20190107_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, db_column='Password', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='resetcode',
            field=models.CharField(blank=True, db_column='ResetCode', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, db_column='Username', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='accounttypename',
            field=models.CharField(blank=True, db_column='AccountTypeName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityname',
            field=models.CharField(blank=True, db_column='ActivityName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittion',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitysubmittionreply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='activitytypename',
            field=models.CharField(blank=True, db_column='ActivityTypeName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chaptername',
            field=models.CharField(blank=True, db_column='ChapterName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitionname',
            field=models.CharField(blank=True, db_column='CompetitionName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittion',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmittionlike',
            name='note',
            field=models.CharField(db_column='Note', max_length=250),
        ),
        migrations.AlterField(
            model_name='competitionsubmittionreply',
            name='note',
            field=models.CharField(db_column='Note', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enviromentcate',
            name='enviromentcatename',
            field=models.CharField(blank=True, db_column='EnviromentCateName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enviromentcate',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fastchat',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footername',
            field=models.CharField(blank=True, db_column='FooterName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='image',
            field=models.CharField(blank=True, db_column='Image', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='forumtopicname',
            field=models.CharField(blank=True, db_column='ForumTopicName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forumlike',
            name='note',
            field=models.CharField(db_column='Note', max_length=250),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='headername',
            field=models.CharField(blank=True, db_column='HeaderName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.CharField(blank=True, db_column='Image', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='homename',
            field=models.CharField(blank=True, db_column='HomeName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.CharField(blank=True, db_column='Image', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.CharField(blank=True, db_column='Image', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='introductionname',
            field=models.CharField(blank=True, db_column='IntroductionName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(blank=True, db_column='ItemName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessonname',
            field=models.CharField(blank=True, db_column='LessonName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lessonreply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsname',
            field=models.CharField(blank=True, db_column='NewsName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newsreply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='projectsharetopicname',
            field=models.CharField(blank=True, db_column='ProjectShareTopicName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectsharelike',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectsharereply',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sliderunbar',
            name='image',
            field=models.CharField(blank=True, db_column='Image', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sliderunbar',
            name='link',
            field=models.CharField(blank=True, db_column='Link', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sliderunbar',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sliderunbar',
            name='sliderunbarname',
            field=models.CharField(blank=True, db_column='SlideRunBarName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='introvideo',
            field=models.CharField(blank=True, db_column='IntroVideo', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(blank=True, db_column='SubjectName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subjectlike',
            name='note',
            field=models.CharField(db_column='Note', max_length=250),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpart',
            name='subjectpartname',
            field=models.CharField(blank=True, db_column='SubjectPartName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='firstname',
            field=models.CharField(blank=True, db_column='FirstName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lastname',
            field=models.CharField(blank=True, db_column='LastName', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phonenumber',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='icon',
            field=models.CharField(blank=True, db_column='Icon', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='userrankname',
            field=models.CharField(blank=True, db_column='UserRankName', max_length=250, null=True),
        ),
    ]
