# Generated by Django 2.1.3 on 2019-01-10 06:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0032_auto_20190108_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(db_column='GameID', primary_key=True, serialize=False)),
                ('gamename', models.CharField(blank=True, db_column='GameName', max_length=250, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=250, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Content', null=True)),
                ('avatar', models.CharField(blank=True, db_column='Avatar', max_length=250, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('viewcount', models.IntegerField(blank=True, db_column='ViewCount', null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=250, null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account')),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameRate',
            fields=[
                ('gamerateid', models.AutoField(db_column='GameRateID', primary_key=True, serialize=False)),
                ('rate', models.IntegerField(blank=True, db_column='Rate', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Account')),
                ('gameid', models.ForeignKey(blank=True, db_column='GameID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Game')),
            ],
            options={
                'db_table': 'gamerate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('gametypeid', models.AutoField(db_column='GameTypeID', primary_key=True, serialize=False)),
                ('gametypename', models.CharField(blank=True, db_column='GameTypeName', max_length=250, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('editdate', models.DateTimeField(blank=True, db_column='EditDate', null=True)),
            ],
            options={
                'db_table': 'gametype',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='news',
            name='avatar',
            field=models.CharField(blank=True, db_column='Avatar', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gametypeid',
            field=models.ForeignKey(blank=True, db_column='GameTypeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.GameType'),
        ),
        migrations.AddField(
            model_name='game',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdetail.Subject'),
        ),
    ]
