"""
Django settings for baitapthu2 project.

Generated by 'django-admin startproject' using Django 2.1b1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j*4*k6d1k7(^&ejc7yezomn3o^s*0q9_xl+9vnx=h%or88c-b)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'homepage',
    'course',
    # ckeditor
    'ckeditor',
    'ckeditor_uploader',
    # module
    'userforum',
    'usercompetition',
    'userprojectshare',
    'usergame',
    'usernews',
    
    # Admin
    'adminaccounttype',
    'adminenviromentcate',
    'adminaccount',
    'adminuserdetail',
    'adminsubjectteacher',
    'adminsubject',
    'adminsubjectpart',
    'adminsubjectlike',
    'adminchapter',
    'adminlesson',
    'adminitem',
    'adminactivitytype',
    'adminactivity',
    'adminactivityreply',
    'adminactivitysubmittion',
    'adminforum',
    'adminnews',
    'adminprojectshare',
    'admincompetition',
    'admincompetitionsubmittion',
    'adminenrollment',
    'adminlessonreply',
    'adminactivitysubmittionreply',
    'admintracking',
    'adminforumlike',
    'adminforumreply',
    'adminnewsreply',
    'adminprojectsharereply',
    'adminprojectsharelike',
    'admincompetitionsubmittionlike',
    'admincompetitionsubmittionreply',
    'adminintroduction',
    'adminheader',
    'adminfooter',
    'adminhome',
    'adminsliderunbar',
    'adminuserrank',
    'admincontact',
    'adminfastchat',
    'admingametype',
    'admingamerate',
    'admingame',
    'adminpage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




ROOT_URLCONF = 'CourseProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, "template")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'CourseProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'VS-Pro',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'vsprodhsp@gmail.com'
EMAIL_HOST_PASSWORD = 'Abcd@123'
EMAIL_USE_TLS= True
EMAIL_USE_SSL= False

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = ''
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}
SESSION_COOKIE_AGE = 43200
